include(":CustomNicknameFormat")
include(":CustomTimestamps")
include(":Experiments")
include(":HideDisabledEmojis")
include(":MessageLogger")
include(":MoreSlashCommands")
include(":NoAutoReplyMention")
include(":NoCopyEmbeds")
include(":PronounDB")
include(":RemoveZoomLimit")
include(":RestoreImageLinks")
include(":SquareAvatars")
include(":Tags")
include(":UserDetails")
include(":ViewRaw")
rootProject.name = "plugins"

include(":Aliucord")
project(":Aliucord").projectDir = File("../repo/Aliucord")
include(":DiscordStubs")
project(":DiscordStubs").projectDir = File("../repo/DiscordStubs")
